# Generated by Django 2.2.6 on 2019-12-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_auto_20191212_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit'),
        ),
    ]
