# Generated by Django 2.2.6 on 2019-12-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0003_auto_20191212_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sudah Masuk'), (2, 'Ditanggapi'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')], default=0),
        ),
    ]
