# Generated by Django 2.2.6 on 2019-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0004_laporan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Waktu Submit'),
        ),
    ]
