# Generated by Django 2.2.6 on 2019-12-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0006_auto_20191212_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='masterdata.Kategori'),
        ),
    ]
