# Generated by Django 2.2.6 on 2019-12-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0008_auto_20191213_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='daerah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='masterdata.Kecamatan'),
        ),
    ]
