# Generated by Django 2.2.6 on 2019-12-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0011_laporan_kategori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='daerah',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='kategori',
        ),
    ]
