# Generated by Django 2.2.6 on 2019-12-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0013_laporan_daerah'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
