# Generated by Django 2.2.6 on 2019-12-13 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laporan', '0016_auto_20191213_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(choices=[(1, 'Setuju'), (0, 'Tidak Setuju')])),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='laporan.Laporan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField(max_length=1024)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='laporan.Laporan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
