# Generated by Django 2.2.6 on 2019-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0017_komentar_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[(1, 'Setuju'), (0, 'Tidak Setuju')], max_length=10),
        ),
    ]
