# Generated by Django 2.2.6 on 2019-12-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0019_auto_20191213_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(choices=[(1, 'Setuju'), (0, 'Tidak Setuju')]),
        ),
    ]
