# Generated by Django 2.2.6 on 2019-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0020_auto_20191213_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Sudah Masuk'), (2, 'Ditanggapi'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')], default=1),
        ),
    ]
